version: "3.3"

#Docker Networks
networks:
  common:
    driver: bridge
#Volumes
volumes:
  MYSQL:
    driver: local
  REDIS:
    driver: local
  MONGO:
    driver: local
  POSTGRES:
    driver: local

services:
  # Mysql service
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: webdevel
    volumes:
      - MYSQL:/var/lib/mysql/
      - C:/CODE/docker/mysql/8.0/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - common

  # Phpmyadmin service
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - common
    depends_on:
      - mysql

  # Redis service
  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - 6379:6379
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - REDIS:/data
    networks:
      - common

  # Mongo service
  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
    container_name: mongo
    restart: always
    volumes:
      - MONGO:/data/db
    networks:
      - common

  # Postgres
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: webdevel
    ports:
      - 5432:5432
    volumes:
      - POSTGRES:/var/lib/postgresql/data

  # Adminier
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
